on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 9 * * 4'

jobs:
  SCS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:     
      - uses: actions/checkout@v2

      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@main

      - name: Build
        run: |
          dotnet restore
          dotnet build /p:ErrorLog=analysis.sarif
        
      - name: Convert sarif for uploading to GitHub
        uses: jarlob/security-code-scan-results-action@main
        
      - name: Upload sarif	
        uses: github/codeql-action/upload-sarif@v1
